trigger:
- DocuSignWordfiles

pool:
  vmImage: ubuntu-latest

variables:
- name: VERCEL_PROJECT_ID
  value: 'prj_3NJ50azpNT5OKeTof6mPr18c7fi0'
- name: VERCEL_ORG_ID
  value: 'team_fhA85kClq1piD12QCIwYK8Qq'
- group: frontend-env-vars

steps:
- checkout: self

- script: |
    npm install -g vercel
  displayName: 'Install Vercel CLI'

- script: |
    vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
  displayName: 'Pull Vercel Preview Settings'
  env:
    VERCEL_ORG_ID: $(VERCEL_ORG_ID)
    VERCEL_PROJECT_ID: $(VERCEL_PROJECT_ID)
    VERCEL_TOKEN: $(VERCEL_TOKEN)

- script: |
    vercel build --token=$VERCEL_TOKEN
  displayName: 'Build Vercel Preview'
  env:
    VERCEL_ORG_ID: $(VERCEL_ORG_ID)
    VERCEL_PROJECT_ID: $(VERCEL_PROJECT_ID)
    VERCEL_TOKEN: $(VERCEL_TOKEN)
    NEXT_PUBLIC_API_URL: $(NEXT_PUBLIC_API_URL)
    NEXT_PUBLIC_BASE_URL: $(NEXT_PUBLIC_BASE_URL)
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: $(NEXT_PUBLIC_GOOGLE_CLIENT_ID)
    NEXT_PUBLIC_PAYPAL_CLIENT_ID: $(NEXT_PUBLIC_PAYPAL_CLIENT_ID)
    NEXT_PUBLIC_TAWK_PROPERTY_ID: $(NEXT_PUBLIC_TAWK_PROPERTY_ID)
    NEXT_PUBLIC_TAWK_WIDGET_ID: $(NEXT_PUBLIC_TAWK_WIDGET_ID)

- script: |
    vercel deploy --prebuilt --token=$VERCEL_TOKEN
  displayName: 'Deploy to Vercel Preview'
  env:
    VERCEL_ORG_ID: $(VERCEL_ORG_ID)
    VERCEL_PROJECT_ID: $(VERCEL_PROJECT_ID)
    VERCEL_TOKEN: $(VERCEL_TOKEN)