"use client";

import * as React from "react";
import { useTranslations } from "next-intl";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { CurrencyAmount } from "./currency-amount";

const BUSINESS_ACTIVITIES = [
  // ── A – Agriculture, Forestry & Fishing ──
  { value: "01.11", label: "Growing of cereals (except rice), leguminous crops and oil seeds" },
  { value: "01.12", label: "Growing of rice" },
  { value: "01.13", label: "Growing of vegetables and melons, roots and tubers" },
  { value: "01.14", label: "Growing of sugar cane" },
  { value: "01.15", label: "Growing of tobacco" },
  { value: "01.16", label: "Growing of fibre crops" },
  { value: "01.19", label: "Growing of other non-perennial crops" },
  { value: "01.21", label: "Growing of grapes" },
  { value: "01.22", label: "Growing of tropical and subtropical fruits" },
  { value: "01.23", label: "Growing of citrus fruits" },
  { value: "01.24", label: "Growing of pome fruits and stone fruits" },
  { value: "01.25", label: "Growing of other tree and bush fruits and nuts" },
  { value: "01.26", label: "Growing of oleaginous fruits" },
  { value: "01.27", label: "Growing of beverage crops" },
  { value: "01.28", label: "Growing of spices, aromatic, drug and pharmaceutical crops" },
  { value: "01.29", label: "Growing of other perennial crops" },
  { value: "01.30", label: "Plant propagation" },
  { value: "01.41", label: "Raising of dairy cattle" },
  { value: "01.42", label: "Raising of other cattle and buffaloes" },
  { value: "01.43", label: "Raising of horses and other equines" },
  { value: "01.44", label: "Raising of camels and camelids" },
  { value: "01.45", label: "Raising of sheep and goats" },
  { value: "01.46", label: "Raising of swine/pigs" },
  { value: "01.47", label: "Raising of poultry" },
  { value: "01.49", label: "Raising of other animals" },
  { value: "01.50", label: "Mixed farming" },
  { value: "01.61", label: "Support activities for crop production" },
  { value: "01.62", label: "Support activities for animal production" },
  { value: "01.63", label: "Post-harvest crop activities" },
  { value: "01.64", label: "Seed processing for propagation" },
  { value: "01.70", label: "Hunting, trapping and related service activities" },
  { value: "02.10", label: "Silviculture and other forestry activities" },
  { value: "02.20", label: "Logging" },
  { value: "02.30", label: "Gathering of wild growing non-wood products" },
  { value: "02.40", label: "Support services to forestry" },
  { value: "03.11", label: "Marine fishing" },
  { value: "03.12", label: "Freshwater fishing" },
  { value: "03.21", label: "Marine aquaculture" },
  { value: "03.22", label: "Freshwater aquaculture" },
  // ── B – Mining & Quarrying ──
  { value: "05.10", label: "Mining of hard coal" },
  { value: "05.20", label: "Mining of lignite" },
  { value: "06.10", label: "Extraction of crude petroleum" },
  { value: "06.20", label: "Extraction of natural gas" },
  { value: "07.10", label: "Mining of iron ores" },
  { value: "07.21", label: "Mining of uranium and thorium ores" },
  { value: "07.29", label: "Mining of other non-ferrous metal ores" },
  { value: "08.11", label: "Quarrying of ornamental and building stone" },
  { value: "08.12", label: "Operation of gravel and sand pits; mining of clays and kaolin" },
  { value: "08.91", label: "Mining of chemical and fertiliser minerals" },
  { value: "08.92", label: "Extraction of peat" },
  { value: "08.93", label: "Extraction of salt" },
  { value: "08.99", label: "Other mining and quarrying n.e.c." },
  { value: "09.10", label: "Support activities for petroleum and natural gas extraction" },
  { value: "09.90", label: "Support activities for other mining and quarrying" },
  // ── C – Manufacturing ──
  { value: "10.11", label: "Processing and preserving of meat" },
  { value: "10.12", label: "Processing and preserving of poultry meat" },
  { value: "10.13", label: "Production of meat and poultry meat products" },
  { value: "10.20", label: "Processing and preserving of fish, crustaceans and molluscs" },
  { value: "10.31", label: "Processing and preserving of potatoes" },
  { value: "10.32", label: "Manufacture of fruit and vegetable juice" },
  { value: "10.39", label: "Other processing and preserving of fruit and vegetables" },
  { value: "10.41", label: "Manufacture of oils and fats" },
  { value: "10.42", label: "Manufacture of margarine and similar edible fats" },
  { value: "10.51", label: "Operation of dairies and cheese making" },
  { value: "10.52", label: "Manufacture of ice cream" },
  { value: "10.61", label: "Manufacture of grain mill products" },
  { value: "10.62", label: "Manufacture of starches and starch products" },
  { value: "10.71", label: "Manufacture of bread; manufacture of fresh pastry goods and cakes" },
  { value: "10.72", label: "Manufacture of rusks and biscuits; preserved pastry goods and cakes" },
  { value: "10.73", label: "Manufacture of macaroni, noodles, couscous and similar farinaceous products" },
  { value: "10.81", label: "Manufacture of sugar" },
  { value: "10.82", label: "Manufacture of cocoa, chocolate and sugar confectionery" },
  { value: "10.83", label: "Processing of tea and coffee" },
  { value: "10.84", label: "Manufacture of condiments and seasonings" },
  { value: "10.85", label: "Manufacture of prepared meals and dishes" },
  { value: "10.86", label: "Manufacture of homogenised food preparations and dietetic food" },
  { value: "10.89", label: "Manufacture of other food products n.e.c." },
  { value: "10.91", label: "Manufacture of prepared feeds for farm animals" },
  { value: "10.92", label: "Manufacture of prepared pet foods" },
  { value: "11.01", label: "Distilling, rectifying and blending of spirits" },
  { value: "11.02", label: "Manufacture of wine from grape" },
  { value: "11.03", label: "Manufacture of cider and other fruit wines" },
  { value: "11.04", label: "Manufacture of other non-distilled fermented beverages" },
  { value: "11.05", label: "Manufacture of beer" },
  { value: "11.06", label: "Manufacture of malt" },
  { value: "11.07", label: "Manufacture of soft drinks; production of mineral waters and other bottled waters" },
  { value: "12.00", label: "Manufacture of tobacco products" },
  { value: "13.10", label: "Preparation and spinning of textile fibres" },
  { value: "13.20", label: "Weaving of textiles" },
  { value: "13.30", label: "Finishing of textiles" },
  { value: "13.91", label: "Manufacture of knitted and crocheted fabrics" },
  { value: "13.92", label: "Manufacture of made-up textile articles, except apparel" },
  { value: "13.93", label: "Manufacture of carpets and rugs" },
  { value: "13.94", label: "Manufacture of cordage, rope, twine and netting" },
  { value: "13.95", label: "Manufacture of non-wovens and articles made from non-wovens" },
  { value: "13.96", label: "Manufacture of other technical and industrial textiles" },
  { value: "13.99", label: "Manufacture of other textiles n.e.c." },
  { value: "14.11", label: "Manufacture of leather clothes" },
  { value: "14.12", label: "Manufacture of workwear" },
  { value: "14.13", label: "Manufacture of other outerwear" },
  { value: "14.14", label: "Manufacture of underwear" },
  { value: "14.19", label: "Manufacture of other wearing apparel and accessories" },
  { value: "14.20", label: "Manufacture of articles of fur" },
  { value: "14.31", label: "Manufacture of knitted and crocheted hosiery" },
  { value: "14.39", label: "Manufacture of other knitted and crocheted apparel" },
  { value: "15.11", label: "Tanning and dressing of leather; dressing and dyeing of fur" },
  { value: "15.12", label: "Manufacture of luggage, handbags and the like, saddlery and harness" },
  { value: "15.20", label: "Manufacture of footwear" },
  { value: "16.10", label: "Sawmilling and planing of wood" },
  { value: "16.21", label: "Manufacture of veneer sheets and wood-based panels" },
  { value: "16.22", label: "Manufacture of assembled parquet floors" },
  { value: "16.23", label: "Manufacture of other builders' carpentry and joinery" },
  { value: "16.24", label: "Manufacture of wooden containers" },
  { value: "16.29", label: "Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials" },
  { value: "17.11", label: "Manufacture of pulp" },
  { value: "17.12", label: "Manufacture of paper and paperboard" },
  { value: "17.21", label: "Manufacture of corrugated paper and paperboard and of containers" },
  { value: "17.22", label: "Manufacture of household and sanitary goods and of toilet requisites" },
  { value: "17.23", label: "Manufacture of paper stationery" },
  { value: "17.24", label: "Manufacture of wallpaper" },
  { value: "17.29", label: "Manufacture of other articles of paper and paperboard" },
  { value: "18.11", label: "Printing of newspapers" },
  { value: "18.12", label: "Other printing" },
  { value: "18.13", label: "Pre-press and pre-media services" },
  { value: "18.14", label: "Binding and related services" },
  { value: "18.20", label: "Reproduction of recorded media" },
  { value: "19.10", label: "Manufacture of coke oven products" },
  { value: "19.20", label: "Manufacture of refined petroleum products" },
  { value: "20.11", label: "Manufacture of industrial gases" },
  { value: "20.12", label: "Manufacture of dyes and pigments" },
  { value: "20.13", label: "Manufacture of other inorganic basic chemicals" },
  { value: "20.14", label: "Manufacture of other organic basic chemicals" },
  { value: "20.15", label: "Manufacture of fertilisers and nitrogen compounds" },
  { value: "20.16", label: "Manufacture of plastics in primary forms" },
  { value: "20.17", label: "Manufacture of synthetic rubber in primary forms" },
  { value: "20.20", label: "Manufacture of pesticides and other agrochemical products" },
  { value: "20.30", label: "Manufacture of paints, varnishes and similar coatings, printing ink and mastics" },
  { value: "20.41", label: "Manufacture of soap and detergents, cleaning and polishing preparations" },
  { value: "20.42", label: "Manufacture of perfumes and toilet preparations" },
  { value: "20.51", label: "Manufacture of explosives" },
  { value: "20.52", label: "Manufacture of glues" },
  { value: "20.53", label: "Manufacture of essential oils" },
  { value: "20.59", label: "Manufacture of other chemical products n.e.c." },
  { value: "20.60", label: "Manufacture of man-made fibres" },
  { value: "21.10", label: "Manufacture of basic pharmaceutical products" },
  { value: "21.20", label: "Manufacture of pharmaceutical preparations" },
  { value: "22.11", label: "Manufacture of rubber tyres and tubes" },
  { value: "22.19", label: "Manufacture of other rubber products" },
  { value: "22.21", label: "Manufacture of plastic plates, sheets, tubes and profiles" },
  { value: "22.22", label: "Manufacture of plastic packing goods" },
  { value: "22.23", label: "Manufacture of builders' ware of plastic" },
  { value: "22.29", label: "Manufacture of other plastic products" },
  { value: "23.11", label: "Manufacture of flat glass" },
  { value: "23.12", label: "Shaping and processing of flat glass" },
  { value: "23.13", label: "Manufacture of hollow glass" },
  { value: "23.14", label: "Manufacture of glass fibres" },
  { value: "23.19", label: "Manufacture and processing of other glass, including technical glassware" },
  { value: "23.20", label: "Manufacture of refractory products" },
  { value: "23.31", label: "Manufacture of ceramic tiles and flags" },
  { value: "23.32", label: "Manufacture of bricks, tiles and construction products, in baked clay" },
  { value: "23.41", label: "Manufacture of ceramic household and ornamental articles" },
  { value: "23.42", label: "Manufacture of ceramic sanitary fixtures" },
  { value: "23.43", label: "Manufacture of ceramic insulators and insulating fittings" },
  { value: "23.44", label: "Manufacture of other technical ceramic products" },
  { value: "23.49", label: "Manufacture of other ceramic products" },
  { value: "23.51", label: "Manufacture of cement" },
  { value: "23.52", label: "Manufacture of lime and plaster" },
  { value: "23.61", label: "Manufacture of concrete products for construction purposes" },
  { value: "23.62", label: "Manufacture of plaster products for construction purposes" },
  { value: "23.63", label: "Manufacture of ready-mixed concrete" },
  { value: "23.64", label: "Manufacture of mortars" },
  { value: "23.65", label: "Manufacture of fibre cement" },
  { value: "23.69", label: "Manufacture of other articles of concrete, plaster and cement" },
  { value: "23.70", label: "Cutting, shaping and finishing of stone" },
  { value: "23.91", label: "Production of abrasive products" },
  { value: "23.99", label: "Manufacture of other non-metallic mineral products n.e.c." },
  { value: "24.10", label: "Manufacture of basic iron and steel and of ferro-alloys" },
  { value: "24.20", label: "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel" },
  { value: "24.31", label: "Cold drawing of bars" },
  { value: "24.32", label: "Cold rolling of narrow strip" },
  { value: "24.33", label: "Cold forming or folding" },
  { value: "24.34", label: "Cold drawing of wire" },
  { value: "24.41", label: "Precious metals production" },
  { value: "24.42", label: "Aluminium production" },
  { value: "24.43", label: "Lead, zinc and tin production" },
  { value: "24.44", label: "Copper production" },
  { value: "24.45", label: "Other non-ferrous metal production" },
  { value: "24.46", label: "Processing of nuclear fuel" },
  { value: "24.51", label: "Casting of iron" },
  { value: "24.52", label: "Casting of steel" },
  { value: "24.53", label: "Casting of light metals" },
  { value: "24.54", label: "Casting of other non-ferrous metals" },
  { value: "25.11", label: "Manufacture of metal structures and parts of structures" },
  { value: "25.12", label: "Manufacture of doors and windows of metal" },
  { value: "25.21", label: "Manufacture of central heating radiators and boilers" },
  { value: "25.29", label: "Manufacture of other tanks, reservoirs and containers of metal" },
  { value: "25.30", label: "Manufacture of steam generators" },
  { value: "25.40", label: "Manufacture of weapons and ammunition" },
  { value: "25.50", label: "Forging, pressing, stamping and roll-forming of metal" },
  { value: "25.61", label: "Treatment and coating of metals" },
  { value: "25.62", label: "Machining" },
  { value: "25.71", label: "Manufacture of cutlery" },
  { value: "25.72", label: "Manufacture of locks and hinges" },
  { value: "25.73", label: "Manufacture of tools" },
  { value: "25.91", label: "Manufacture of steel drums and similar containers" },
  { value: "25.92", label: "Manufacture of light metal packaging" },
  { value: "25.93", label: "Manufacture of wire products, chain and springs" },
  { value: "25.94", label: "Manufacture of fasteners and screw machine products" },
  { value: "25.99", label: "Manufacture of other fabricated metal products n.e.c." },
  { value: "26.11", label: "Manufacture of electronic components" },
  { value: "26.12", label: "Manufacture of loaded electronic boards" },
  { value: "26.20", label: "Manufacture of computers and peripheral equipment" },
  { value: "26.30", label: "Manufacture of communication equipment" },
  { value: "26.40", label: "Manufacture of consumer electronics" },
  { value: "26.51", label: "Manufacture of instruments and appliances for measuring" },
  { value: "26.52", label: "Manufacture of watches and clocks" },
  { value: "26.60", label: "Manufacture of irradiation, electromedical and electrotherapeutic equipment" },
  { value: "26.70", label: "Manufacture of optical instruments and photographic equipment" },
  { value: "26.80", label: "Manufacture of magnetic and optical media" },
  { value: "27.11", label: "Manufacture of electric motors, generators and transformers" },
  { value: "27.12", label: "Manufacture of electricity distribution and control apparatus" },
  { value: "27.20", label: "Manufacture of batteries and accumulators" },
  { value: "27.31", label: "Manufacture of fibre optic cables" },
  { value: "27.32", label: "Manufacture of other electronic and electric wires and cables" },
  { value: "27.33", label: "Manufacture of wiring devices" },
  { value: "27.40", label: "Manufacture of electric lighting equipment" },
  { value: "27.51", label: "Manufacture of electric domestic appliances" },
  { value: "27.52", label: "Manufacture of non-electric domestic appliances" },
  { value: "27.90", label: "Manufacture of other electrical equipment" },
  { value: "28.11", label: "Manufacture of engines and turbines" },
  { value: "28.12", label: "Manufacture of fluid power equipment" },
  { value: "28.13", label: "Manufacture of other pumps and compressors" },
  { value: "28.14", label: "Manufacture of other taps and valves" },
  { value: "28.15", label: "Manufacture of bearings, gears, gearing and driving elements" },
  { value: "28.21", label: "Manufacture of ovens, furnaces and furnace burners" },
  { value: "28.22", label: "Manufacture of lifting and handling equipment" },
  { value: "28.23", label: "Manufacture of office machinery and equipment (except computers and peripheral equipment)" },
  { value: "28.24", label: "Manufacture of power-driven hand tools" },
  { value: "28.25", label: "Manufacture of non-domestic cooling and ventilation equipment" },
  { value: "28.29", label: "Manufacture of other general-purpose machinery n.e.c." },
  { value: "28.30", label: "Manufacture of agricultural and forestry machinery" },
  { value: "28.41", label: "Manufacture of metal forming machinery" },
  { value: "28.49", label: "Manufacture of other machine tools" },
  { value: "28.91", label: "Manufacture of machinery for metallurgy" },
  { value: "28.92", label: "Manufacture of machinery for mining, quarrying and construction" },
  { value: "28.93", label: "Manufacture of machinery for food, beverage and tobacco processing" },
  { value: "28.94", label: "Manufacture of machinery for textile, apparel and leather production" },
  { value: "28.95", label: "Manufacture of machinery for paper and paperboard production" },
  { value: "28.96", label: "Manufacture of plastics and rubber machinery" },
  { value: "28.99", label: "Manufacture of other special-purpose machinery n.e.c." },
  { value: "29.10", label: "Manufacture of motor vehicles" },
  { value: "29.20", label: "Manufacture of bodies (coachwork) for motor vehicles" },
  { value: "29.31", label: "Manufacture of electrical and electronic equipment for motor vehicles" },
  { value: "29.32", label: "Manufacture of other parts and accessories for motor vehicles" },
  { value: "30.11", label: "Building of ships and floating structures" },
  { value: "30.12", label: "Building of pleasure and sporting boats" },
  { value: "30.20", label: "Manufacture of railway locomotives and rolling stock" },
  { value: "30.30", label: "Manufacture of air and spacecraft and related machinery" },
  { value: "30.40", label: "Manufacture of military fighting vehicles" },
  { value: "30.91", label: "Manufacture of motorcycles" },
  { value: "30.92", label: "Manufacture of bicycles and invalid carriages" },
  { value: "30.99", label: "Manufacture of other transport equipment n.e.c." },
  { value: "31.01", label: "Manufacture of office and shop furniture" },
  { value: "31.02", label: "Manufacture of kitchen furniture" },
  { value: "31.03", label: "Manufacture of mattresses" },
  { value: "31.09", label: "Manufacture of other furniture" },
  { value: "32.11", label: "Striking of coins" },
  { value: "32.12", label: "Manufacture of jewellery and related articles" },
  { value: "32.13", label: "Manufacture of imitation jewellery and related articles" },
  { value: "32.20", label: "Manufacture of musical instruments" },
  { value: "32.30", label: "Manufacture of sports goods" },
  { value: "32.40", label: "Manufacture of games and toys" },
  { value: "32.50", label: "Manufacture of medical and dental instruments and supplies" },
  { value: "32.91", label: "Manufacture of brooms and brushes" },
  { value: "32.99", label: "Other manufacturing n.e.c." },
  { value: "33.11", label: "Repair of fabricated metal products" },
  { value: "33.12", label: "Repair of machinery" },
  { value: "33.13", label: "Repair of electronic and optical equipment" },
  { value: "33.14", label: "Repair of electrical equipment" },
  { value: "33.15", label: "Repair and maintenance of ships and boats" },
  { value: "33.16", label: "Repair and maintenance of aircraft and spacecraft" },
  { value: "33.17", label: "Repair and maintenance of other transport equipment" },
  { value: "33.19", label: "Repair of other equipment" },
  { value: "33.20", label: "Installation of industrial machinery and equipment" },
  // ── D – Electricity, Gas, Steam ──
  { value: "35.11", label: "Production of electricity" },
  { value: "35.12", label: "Transmission of electricity" },
  { value: "35.13", label: "Distribution of electricity" },
  { value: "35.14", label: "Trade of electricity" },
  { value: "35.21", label: "Manufacture of gas" },
  { value: "35.22", label: "Distribution of gaseous fuels through mains" },
  { value: "35.23", label: "Trade of gas through mains" },
  { value: "35.30", label: "Steam and air conditioning supply" },
  // ── E – Water Supply, Sewerage, Waste ──
  { value: "36.00", label: "Water collection, treatment and supply" },
  { value: "37.00", label: "Sewerage" },
  { value: "38.11", label: "Collection of non-hazardous waste" },
  { value: "38.12", label: "Collection of hazardous waste" },
  { value: "38.21", label: "Treatment and disposal of non-hazardous waste" },
  { value: "38.22", label: "Treatment and disposal of hazardous waste" },
  { value: "38.31", label: "Dismantling of wrecks" },
  { value: "38.32", label: "Recovery of sorted materials" },
  { value: "39.00", label: "Remediation activities and other waste management services" },
  // ── F – Construction ──
  { value: "41.10", label: "Development of building projects" },
  { value: "41.20", label: "Construction of residential and non-residential buildings" },
  { value: "42.11", label: "Construction of roads and motorways" },
  { value: "42.12", label: "Construction of railways and underground railways" },
  { value: "42.13", label: "Construction of bridges and tunnels" },
  { value: "42.21", label: "Construction of utility projects for fluids" },
  { value: "42.22", label: "Construction of utility projects for electricity and telecommunications" },
  { value: "42.91", label: "Construction of water projects" },
  { value: "42.99", label: "Construction of other civil engineering projects n.e.c." },
  { value: "43.11", label: "Demolition" },
  { value: "43.12", label: "Site preparation" },
  { value: "43.13", label: "Test drilling and boring" },
  { value: "43.21", label: "Electrical installation" },
  { value: "43.22", label: "Plumbing, heat and air-conditioning installation" },
  { value: "43.29", label: "Other construction installation" },
  { value: "43.31", label: "Plastering" },
  { value: "43.32", label: "Joinery installation" },
  { value: "43.33", label: "Floor and wall covering" },
  { value: "43.34", label: "Painting and glazing" },
  { value: "43.39", label: "Other building completion and finishing" },
  { value: "43.91", label: "Roofing activities" },
  { value: "43.99", label: "Other specialised construction activities n.e.c." },
  // ── G – Wholesale & Retail Trade ──
  { value: "45.11", label: "Sale of cars and light motor vehicles" },
  { value: "45.19", label: "Sale of other motor vehicles" },
  { value: "45.20", label: "Maintenance and repair of motor vehicles" },
  { value: "45.31", label: "Wholesale trade of motor vehicle parts and accessories" },
  { value: "45.32", label: "Retail trade of motor vehicle parts and accessories" },
  { value: "45.40", label: "Sale, maintenance and repair of motorcycles and related parts" },
  { value: "46.11", label: "Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods" },
  { value: "46.12", label: "Agents involved in the sale of fuels, ores, metals and industrial chemicals" },
  { value: "46.13", label: "Agents involved in the sale of timber and building materials" },
  { value: "46.14", label: "Agents involved in the sale of machinery, industrial equipment, ships and aircraft" },
  { value: "46.15", label: "Agents involved in the sale of furniture, household goods, hardware and ironmongery" },
  { value: "46.16", label: "Agents involved in the sale of textiles, clothing, fur, footwear and leather goods" },
  { value: "46.17", label: "Agents involved in the sale of food, beverages and tobacco" },
  { value: "46.18", label: "Agents specialised in the sale of other particular products" },
  { value: "46.19", label: "Agents involved in the sale of a variety of goods" },
  { value: "46.21", label: "Wholesale of grain, unmanufactured tobacco, seeds and animal feeds" },
  { value: "46.22", label: "Wholesale of flowers and plants" },
  { value: "46.23", label: "Wholesale of live animals" },
  { value: "46.24", label: "Wholesale of hides, skins and leather" },
  { value: "46.31", label: "Wholesale of fruit and vegetables" },
  { value: "46.32", label: "Wholesale of meat and meat products" },
  { value: "46.33", label: "Wholesale of dairy products, eggs and edible oils and fats" },
  { value: "46.34", label: "Wholesale of beverages" },
  { value: "46.35", label: "Wholesale of tobacco products" },
  { value: "46.36", label: "Wholesale of sugar and chocolate and sugar confectionery" },
  { value: "46.37", label: "Wholesale of coffee, tea, cocoa and spices" },
  { value: "46.38", label: "Wholesale of other food, including fish, crustaceans and molluscs" },
  { value: "46.39", label: "Non-specialised wholesale of food, beverages and tobacco" },
  { value: "46.41", label: "Wholesale of textiles" },
  { value: "46.42", label: "Wholesale of clothing and footwear" },
  { value: "46.43", label: "Wholesale of electrical household appliances" },
  { value: "46.44", label: "Wholesale of china and glassware and cleaning materials" },
  { value: "46.45", label: "Wholesale of perfume and cosmetics" },
  { value: "46.46", label: "Wholesale of pharmaceutical goods" },
  { value: "46.47", label: "Wholesale of furniture, carpets and lighting equipment" },
  { value: "46.48", label: "Wholesale of watches and jewellery" },
  { value: "46.49", label: "Wholesale of other household goods" },
  { value: "46.51", label: "Wholesale of computers, computer peripheral equipment and software" },
  { value: "46.52", label: "Wholesale of electronic and telecommunications equipment and parts" },
  { value: "46.61", label: "Wholesale of agricultural machinery, equipment and supplies" },
  { value: "46.62", label: "Wholesale of machine tools" },
  { value: "46.63", label: "Wholesale of mining, construction and civil engineering machinery" },
  { value: "46.64", label: "Wholesale of machinery for the textile industry and of sewing and knitting machines" },
  { value: "46.65", label: "Wholesale of office furniture" },
  { value: "46.66", label: "Wholesale of other office machinery and equipment" },
  { value: "46.69", label: "Wholesale of other machinery and equipment" },
  { value: "46.71", label: "Wholesale of solid, liquid and gaseous fuels and related products" },
  { value: "46.72", label: "Wholesale of metals and metal ores" },
  { value: "46.73", label: "Wholesale of wood, construction materials and sanitary equipment" },
  { value: "46.74", label: "Wholesale of hardware, plumbing and heating equipment and supplies" },
  { value: "46.75", label: "Wholesale of chemical products" },
  { value: "46.76", label: "Wholesale of other intermediate products" },
  { value: "46.77", label: "Wholesale of waste and scrap" },
  { value: "46.90", label: "Non-specialised wholesale trade" },
  { value: "47.11", label: "Retail sale in non-specialised stores with food, beverages or tobacco predominating" },
  { value: "47.19", label: "Other retail sale in non-specialised stores" },
  { value: "47.21", label: "Retail sale of fruit and vegetables" },
  { value: "47.22", label: "Retail sale of meat and meat products" },
  { value: "47.23", label: "Retail sale of fish, crustaceans and molluscs" },
  { value: "47.24", label: "Retail sale of bread, cakes, flour confectionery and sugar confectionery" },
  { value: "47.25", label: "Retail sale of beverages" },
  { value: "47.26", label: "Retail sale of tobacco products" },
  { value: "47.29", label: "Other retail sale of food in specialised stores" },
  { value: "47.30", label: "Retail sale of automotive fuel" },
  { value: "47.41", label: "Retail sale of computers, peripheral units and software" },
  { value: "47.42", label: "Retail sale of telecommunications equipment" },
  { value: "47.43", label: "Retail sale of audio and video equipment" },
  { value: "47.51", label: "Retail sale of textiles" },
  { value: "47.52", label: "Retail sale of hardware, paints and glass" },
  { value: "47.53", label: "Retail sale of carpets, rugs, wall and floor coverings" },
  { value: "47.54", label: "Retail sale of electrical household appliances" },
  { value: "47.59", label: "Retail sale of furniture, lighting equipment and other household articles" },
  { value: "47.61", label: "Retail sale of books" },
  { value: "47.62", label: "Retail sale of newspapers and stationery" },
  { value: "47.63", label: "Retail sale of music and video recordings" },
  { value: "47.64", label: "Retail sale of sporting equipment" },
  { value: "47.65", label: "Retail sale of games and toys" },
  { value: "47.71", label: "Retail sale of clothing" },
  { value: "47.72", label: "Retail sale of footwear and leather goods" },
  { value: "47.73", label: "Dispensing chemist" },
  { value: "47.74", label: "Retail sale of medical and orthopaedic goods" },
  { value: "47.75", label: "Retail sale of cosmetic and toilet articles" },
  { value: "47.76", label: "Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food" },
  { value: "47.77", label: "Retail sale of watches and jewellery" },
  { value: "47.78", label: "Other retail sale of new goods in specialised stores" },
  { value: "47.79", label: "Retail sale of second-hand goods" },
  { value: "47.81", label: "Retail sale via stalls and markets of food, beverages and tobacco products" },
  { value: "47.82", label: "Retail sale via stalls and markets of textiles, clothing and footwear" },
  { value: "47.89", label: "Retail sale via stalls and markets of other goods" },
  { value: "47.91", label: "Retail sale via mail order houses or via Internet" },
  { value: "47.99", label: "Other retail sale not in stores, stalls or markets" },
  // ── H – Transportation & Storage ──
  { value: "49.10", label: "Passenger rail transport, interurban" },
  { value: "49.20", label: "Freight rail transport" },
  { value: "49.31", label: "Urban and suburban passenger land transport" },
  { value: "49.32", label: "Taxi operation" },
  { value: "49.39", label: "Other passenger land transport n.e.c." },
  { value: "49.41", label: "Freight transport by road" },
  { value: "49.42", label: "Removal services" },
  { value: "49.50", label: "Transport via pipeline" },
  { value: "50.10", label: "Sea and coastal passenger water transport" },
  { value: "50.20", label: "Sea and coastal freight water transport" },
  { value: "50.30", label: "Inland passenger water transport" },
  { value: "50.40", label: "Inland freight water transport" },
  { value: "51.10", label: "Passenger air transport" },
  { value: "51.21", label: "Freight air transport" },
  { value: "51.22", label: "Space transport" },
  { value: "52.10", label: "Warehousing and storage" },
  { value: "52.21", label: "Service activities incidental to land transportation" },
  { value: "52.22", label: "Service activities incidental to water transportation" },
  { value: "52.23", label: "Service activities incidental to air transportation" },
  { value: "52.24", label: "Cargo handling" },
  { value: "52.29", label: "Other transportation support activities" },
  { value: "53.10", label: "Postal activities under universal service obligation" },
  { value: "53.20", label: "Other postal and courier activities" },
  // ── I – Accommodation & Food ──
  { value: "55.10", label: "Hotels and similar accommodation" },
  { value: "55.20", label: "Holiday and other short-stay accommodation" },
  { value: "55.30", label: "Camping grounds, recreational vehicle parks and trailer parks" },
  { value: "55.90", label: "Other accommodation" },
  { value: "56.10", label: "Restaurants and mobile food service activities" },
  { value: "56.21", label: "Event catering activities" },
  { value: "56.29", label: "Other food service activities" },
  { value: "56.30", label: "Beverage serving activities" },
  // ── J – Information & Communication ──
  { value: "58.11", label: "Book publishing" },
  { value: "58.12", label: "Publishing of directories and mailing lists" },
  { value: "58.13", label: "Publishing of newspapers" },
  { value: "58.14", label: "Publishing of journals and periodicals" },
  { value: "58.19", label: "Other publishing activities" },
  { value: "58.21", label: "Publishing of computer games" },
  { value: "58.29", label: "Other software publishing" },
  { value: "59.11", label: "Motion picture, video and television programme production activities" },
  { value: "59.12", label: "Motion picture, video and television programme post-production activities" },
  { value: "59.13", label: "Motion picture, video and television programme distribution activities" },
  { value: "59.14", label: "Motion picture projection activities" },
  { value: "59.20", label: "Sound recording and music publishing activities" },
  { value: "60.10", label: "Radio broadcasting" },
  { value: "60.20", label: "Television programming and broadcasting activities" },
  { value: "61.10", label: "Wired telecommunications activities" },
  { value: "61.20", label: "Wireless telecommunications activities" },
  { value: "61.30", label: "Satellite telecommunications activities" },
  { value: "61.90", label: "Other telecommunications activities" },
  { value: "62.01", label: "Computer programming activities" },
  { value: "62.02", label: "Computer consultancy activities" },
  { value: "62.03", label: "Computer facilities management activities" },
  { value: "62.09", label: "Other information technology and computer service activities" },
  { value: "63.11", label: "Data processing, hosting and related activities" },
  { value: "63.12", label: "Web portals" },
  { value: "63.91", label: "News agency activities" },
  { value: "63.99", label: "Other information service activities n.e.c." },
  // ── K – Financial & Insurance ──
  { value: "64.11", label: "Central banking" },
  { value: "64.19", label: "Other monetary intermediation" },
  { value: "64.20", label: "Activities of holding companies" },
  { value: "64.30", label: "Trusts, funds and similar financial entities" },
  { value: "64.91", label: "Financial leasing" },
  { value: "64.92", label: "Other credit granting" },
  { value: "64.99", label: "Other financial service activities, except insurance and pension funding n.e.c." },
  { value: "65.11", label: "Life insurance" },
  { value: "65.12", label: "Non-life insurance" },
  { value: "65.20", label: "Reinsurance" },
  { value: "65.30", label: "Pension funding" },
  { value: "66.11", label: "Administration of financial markets" },
  { value: "66.12", label: "Security and commodity contracts dealing activities" },
  { value: "66.19", label: "Other activities auxiliary to financial services, except insurance and pension funding" },
  { value: "66.21", label: "Risk and damage evaluation" },
  { value: "66.22", label: "Activities of insurance agents and brokers" },
  { value: "66.29", label: "Other activities auxiliary to insurance and pension funding" },
  { value: "66.30", label: "Fund management activities" },
  // ── L – Real Estate ──
  { value: "68.10", label: "Buying and selling of own real estate" },
  { value: "68.20", label: "Renting and operating of own or leased real estate" },
  { value: "68.31", label: "Real estate agencies" },
  { value: "68.32", label: "Management of real estate on a fee or contract basis" },
  // ── M – Professional, Scientific & Technical ──
  { value: "69.10", label: "Legal activities" },
  { value: "69.20", label: "Accounting, bookkeeping and auditing activities; tax consultancy" },
  { value: "70.10", label: "Activities of head offices" },
  { value: "70.21", label: "Public relations and communication activities" },
  { value: "70.22", label: "Business and other management consultancy activities" },
  { value: "71.11", label: "Architectural activities" },
  { value: "71.12", label: "Engineering activities and related technical consultancy" },
  { value: "71.20", label: "Technical testing and analysis" },
  { value: "72.11", label: "Research and experimental development on biotechnology" },
  { value: "72.19", label: "Other research and experimental development on natural sciences and engineering" },
  { value: "72.20", label: "Research and experimental development on social sciences and humanities" },
  { value: "73.11", label: "Advertising agencies" },
  { value: "73.12", label: "Media representation" },
  { value: "73.20", label: "Market research and public opinion polling" },
  { value: "74.10", label: "Specialised design activities" },
  { value: "74.20", label: "Photographic activities" },
  { value: "74.30", label: "Translation and interpretation activities" },
  { value: "74.90", label: "Other professional, scientific and technical activities n.e.c." },
  { value: "75.00", label: "Veterinary activities" },
  // ── N – Administrative & Support Services ──
  { value: "77.11", label: "Renting and leasing of cars and light motor vehicles" },
  { value: "77.12", label: "Renting and leasing of trucks" },
  { value: "77.21", label: "Renting and leasing of recreational and sports goods" },
  { value: "77.22", label: "Renting of video tapes and disks" },
  { value: "77.29", label: "Renting and leasing of other personal and household goods" },
  { value: "77.31", label: "Renting and leasing of agricultural machinery and equipment" },
  { value: "77.32", label: "Renting and leasing of construction and civil engineering machinery and equipment" },
  { value: "77.33", label: "Renting and leasing of office machinery and equipment (including computers)" },
  { value: "77.34", label: "Renting and leasing of water transport equipment" },
  { value: "77.35", label: "Renting and leasing of air transport equipment" },
  { value: "77.39", label: "Renting and leasing of other machinery, equipment and tangible goods n.e.c." },
  { value: "77.40", label: "Leasing of intellectual property and similar products" },
  { value: "78.10", label: "Activities of employment placement agencies" },
  { value: "78.20", label: "Temporary employment agency activities" },
  { value: "78.30", label: "Other human resources provision" },
  { value: "79.11", label: "Travel agency activities" },
  { value: "79.12", label: "Tour operator activities" },
  { value: "79.90", label: "Other reservation service and related activities" },
  { value: "80.10", label: "Private security activities" },
  { value: "80.20", label: "Security systems service activities" },
  { value: "80.30", label: "Investigation activities" },
  { value: "81.10", label: "Combined facilities support activities" },
  { value: "81.21", label: "General cleaning of buildings" },
  { value: "81.22", label: "Other building and industrial cleaning activities" },
  { value: "81.29", label: "Other cleaning activities" },
  { value: "81.30", label: "Landscape service activities" },
  { value: "82.11", label: "Combined office administrative service activities" },
  { value: "82.19", label: "Photocopying, document preparation and other specialised office support activities" },
  { value: "82.20", label: "Activities of call centres" },
  { value: "82.30", label: "Organisation of conventions and trade shows" },
  { value: "82.91", label: "Activities of collection agencies and credit bureaus" },
  { value: "82.92", label: "Packaging activities" },
  { value: "82.99", label: "Other business support service activities n.e.c." },
  // ── O – Public Administration ──
  { value: "84.11", label: "General public administration activities" },
  { value: "84.12", label: "Regulation of the activities of providing health care, education, cultural services and other social services" },
  { value: "84.13", label: "Regulation of and contribution to more efficient operation of businesses" },
  { value: "84.21", label: "Foreign affairs" },
  { value: "84.22", label: "Defence activities" },
  { value: "84.23", label: "Justice and judicial activities" },
  { value: "84.24", label: "Public order and safety activities" },
  { value: "84.25", label: "Fire service activities" },
  { value: "84.30", label: "Compulsory social security activities" },
  // ── P – Education ──
  { value: "85.10", label: "Pre-primary education" },
  { value: "85.20", label: "Primary education" },
  { value: "85.31", label: "General secondary education" },
  { value: "85.32", label: "Technical and vocational secondary education" },
  { value: "85.41", label: "Post-secondary non-tertiary education" },
  { value: "85.42", label: "Tertiary education" },
  { value: "85.51", label: "Sports and recreation education" },
  { value: "85.52", label: "Cultural education" },
  { value: "85.53", label: "Driving school activities" },
  { value: "85.59", label: "Other education n.e.c." },
  { value: "85.60", label: "Educational support activities" },
  // ── Q – Health & Social Work ──
  { value: "86.10", label: "Hospital activities" },
  { value: "86.21", label: "General medical practice activities" },
  { value: "86.22", label: "Specialist medical practice activities" },
  { value: "86.23", label: "Dental practice activities" },
  { value: "86.90", label: "Other human health activities" },
  { value: "87.10", label: "Residential nursing care activities" },
  { value: "87.20", label: "Residential care activities for mental retardation, mental health and substance abuse" },
  { value: "87.30", label: "Residential care activities for the elderly and disabled" },
  { value: "87.90", label: "Other residential care activities" },
  { value: "88.10", label: "Social work activities without accommodation for the elderly and disabled" },
  { value: "88.91", label: "Child day-care activities" },
  { value: "88.99", label: "Other social work activities without accommodation n.e.c." },
  // ── R – Arts, Entertainment & Recreation ──
  { value: "90.01", label: "Performing arts" },
  { value: "90.02", label: "Support activities to performing arts" },
  { value: "90.03", label: "Artistic creation" },
  { value: "90.04", label: "Operation of arts facilities" },
  { value: "91.01", label: "Library and archives activities" },
  { value: "91.02", label: "Museums activities" },
  { value: "91.03", label: "Operation of historical sites and buildings and similar visitor attractions" },
  { value: "91.04", label: "Botanical and zoological gardens and nature reserves activities" },
  { value: "92.00", label: "Gambling and betting activities" },
  { value: "93.11", label: "Operation of sports facilities" },
  { value: "93.12", label: "Activities of sport clubs" },
  { value: "93.13", label: "Fitness facilities" },
  { value: "93.19", label: "Other sports activities" },
  { value: "93.21", label: "Activities of amusement parks and theme parks" },
  { value: "93.29", label: "Other amusement and recreation activities" },
  // ── S – Other Service Activities ──
  { value: "94.11", label: "Activities of business and employers membership organisations" },
  { value: "94.12", label: "Activities of professional membership organisations" },
  { value: "94.20", label: "Activities of trade unions" },
  { value: "94.91", label: "Activities of religious organisations" },
  { value: "94.92", label: "Activities of political organisations" },
  { value: "94.99", label: "Activities of other membership organisations n.e.c." },
  { value: "95.11", label: "Repair of computers and peripheral equipment" },
  { value: "95.12", label: "Repair of communication equipment" },
  { value: "95.21", label: "Repair of consumer electronics" },
  { value: "95.22", label: "Repair of household appliances and home and garden equipment" },
  { value: "95.23", label: "Repair of footwear and leather goods" },
  { value: "95.24", label: "Repair of furniture and home furnishings" },
  { value: "95.25", label: "Repair of watches, clocks and jewellery" },
  { value: "95.29", label: "Repair of other personal and household goods" },
  { value: "96.01", label: "Washing and (dry-)cleaning of textile and fur products" },
  { value: "96.02", label: "Hairdressing and other beauty treatment" },
  { value: "96.03", label: "Funeral and related activities" },
  { value: "96.04", label: "Physical well-being activities" },
  { value: "96.09", label: "Other personal service activities n.e.c." },
  // ── T – Households as Employers ──
  { value: "97.00", label: "Activities of households as employers of domestic personnel" },
  { value: "98.10", label: "Undifferentiated goods-producing activities of private households for own use" },
  { value: "98.20", label: "Undifferentiated service-producing activities of private households for own use" },
  // ── U – Extraterritorial Organisations ──
  { value: "99.00", label: "Activities of extraterritorial organisations and bodies" },
];

interface ActivityScaleStepProps {
  data: any;
  onUpdate: (data: any) => void;
  onNext: () => void;
}

export function ActivityScaleStep({
  data,
  onUpdate,
  onNext,
}: ActivityScaleStepProps) {
  const t = useTranslations();

  const updateField = (field: string, value: any) => {
    onUpdate({ [field]: value });
  };

  const checkValidity = () => {
    if (!data.businessActivity) return false;
    if (!data.turnoverLastFYAmount || data.turnoverLastFYAmount < 0) return false;
    if (!data.turnoverCurrentFYAmount || data.turnoverCurrentFYAmount < 0) return false;
    if (data.employeesFTE === undefined || data.employeesFTE < 0) return false;

    return true;
  };

  // Check validation whenever data changes
  React.useEffect(() => {
    const isValid = checkValidity();
    onUpdate({ isStep2Valid: isValid });
  }, [
    data.businessActivity,
    data.turnoverLastFYAmount,
    data.turnoverCurrentFYAmount,
    data.employeesFTE,
  ]);

  return (
    <div className="space-y-6">
      <div>
        <h2 className="mb-2 text-2xl font-bold text-brand-dark">
          {t('accounting.activityScale.title')}
        </h2>
        <p className="text-brand-grayMed">
          {t('accounting.activityScale.subtitle')}
        </p>
      </div>

      <div className="space-y-4">
        {/* Business Activity */}
        <div>
          <Label className="text-sm font-medium text-brand-dark">
            {t('accounting.activityScale.fields.businessActivity')} <span className="text-red-500">*</span>
          </Label>
          <Select
            value={data.businessActivity || ""}
            onValueChange={(value) => updateField("businessActivity", value)}
          >
            <SelectTrigger>
              <SelectValue placeholder={t('accounting.activityScale.placeholders.businessActivity')} />
            </SelectTrigger>
            <SelectContent>
              {BUSINESS_ACTIVITIES.map((activity) => (
                <SelectItem key={activity.value} value={activity.value}>
                  {activity.label} (NACE {activity.value})
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Annual Turnover (Last FY) */}
        <CurrencyAmount
          label={t('accounting.activityScale.fields.turnoverLastFY')}
          amount={data.turnoverLastFYAmount || 0}
          currency={data.turnoverLastFYCurrency || "EUR"}
          onAmountChange={(amount) =>
            updateField("turnoverLastFYAmount", amount)
          }
          onCurrencyChange={(currency) =>
            updateField("turnoverLastFYCurrency", currency)
          }
          required
          helpText={t('accounting.activityScale.hints.turnoverLastFY')}
        />

        {/* Projected Turnover (Current FY) */}
        <CurrencyAmount
          label={t('accounting.activityScale.fields.turnoverCurrentFY')}
          amount={data.turnoverCurrentFYAmount || 0}
          currency={data.turnoverCurrentFYCurrency || "EUR"}
          onAmountChange={(amount) =>
            updateField("turnoverCurrentFYAmount", amount)
          }
          onCurrencyChange={(currency) =>
            updateField("turnoverCurrentFYCurrency", currency)
          }
          required
          helpText={t('accounting.activityScale.hints.turnoverCurrentFY')}
        />

        {/* Number of Employees */}
        <div>
          <Label className="text-sm font-medium text-brand-dark">
            {t('accounting.activityScale.fields.employees')} <span className="text-red-500">*</span>
          </Label>
          <Input
            type="number"
            min="0"
            step="1"
            value={data.employeesFTE === undefined || data.employeesFTE === 0 ? "" : data.employeesFTE}
            onChange={(e) =>
              updateField("employeesFTE", e.target.value === "" ? undefined : parseInt(e.target.value))
            }
            placeholder=""
          />
          <p className="mt-1 text-xs text-brand-grayMed">
            {t('accounting.activityScale.hints.employees')}
          </p>
        </div>
      </div>
    </div>
  );
}
